// Boy Band — Stage entry point.
//
// Headless CLI that:
//   1. Listens on ws://0.0.0.0:<port>, accepts WS upgrades on:
//        /ws/duck     (real firmware; slot from X-Duck-Id header via duck-map)
//        /duck/{ID}   (test/dev shortcut; slot from path, used by fake-duck.py)
//   2. Logs connect / disconnect / inbound text frames
//   3. Optionally streams a steady sine tone to every connected duck
//      (different pitch per duck so the channel routing is audible)
//
// Usage:
//   swift run BoyBandStage                       # server only, idle
//   swift run BoyBandStage --sine                # stream sine to all
//   swift run BoyBandStage --sine D2             # solo D2; others silent
//   swift run BoyBandStage --port 3334           # explicit port (default 3334)
//   swift run BoyBandStage --duck-map FILE.json  # MAC→slot map
//   swift run BoyBandStage --no-duck-map         # /duck/{ID} only (test mode)
//
// Default duck-map lookup order:
//   ./duck-map.local.json
//   <repo>/boyband/duck-map.local.json
//
// Point a duck's NVS relay_url at ws://<this-mac>.local:3334 to wire it in.
// See boyband/docs/duck-id-mapping.md for the MAC→slot config workflow.

import Foundation
import Dispatch

// MARK: - Args

struct Args {
    var port: UInt16 = 3334
    var sine: Bool = false
    var soloDuck: DuckID? = nil
    /// Explicit map path. nil = use defaults.
    var duckMapPath: String? = nil
    /// If true, don't load any map; /ws/duck connections will be rejected.
    var noDuckMap: Bool = false
    /// Mode 1: read multichannel input from a CoreAudio device.
    var mode1: Bool = false
    /// Substring of the input device name (default "BlackHole"). Ignored
    /// unless --mode1 is set.
    var inputDeviceMatch: String = "BlackHole"
    /// If true, just print all input devices and exit.
    var listInputs: Bool = false
    /// One or more (file → duck) pairs to stream. Repeatable --play lets
    /// us drive multiple ducks with DIFFERENT audio simultaneously — the
    /// core of the multi-duck concept test.
    var plays: [(path: String, duck: DuckID)] = []
    /// Loop the played file(s) instead of stopping after one pass.
    var loop: Bool = false
    /// Pre-load --play tracks but don't auto-start; wait for HTTP /play.
    /// Lets ducks connect+stabilize once, then trigger replays with no
    /// Stage restart (restarts churn duck connections and wedge them).
    var waitTrigger: Bool = false
    /// Preload a directory of chunk files named like NAME_part01_D1.wav.
    /// HTTP /next and /prev switch the active cue without restarting Stage.
    var playlistDir: String? = nil
    /// Preload a per-utterance manifest generated by gen-play-stems.py.
    /// HTTP /play walks line-by-line, streaming only the active speaker.
    var turnManifestPath: String? = nil
    /// Runtime slot aliases for reduced hardware. Example: D3=D1 routes
    /// generated Pintail lines to physical D1.
    var duckAliases: [DuckID: DuckID] = [:]
    /// Per-duck digital gain applied after decode/resample. This is for
    /// matching ElevenLabs voice loudness and individual speaker variance.
    var duckGains: [DuckID: Double] = [
        .D1: 0.56,  // Classic: balanced set multiplied for room volume.
        .D2: 1.24,  // Mallard keeps a relative lift after Loud firmware.
        .D3: 0.78,  // Pintail gets extra presence in the room.
        .D4: 2.47,  // Pekin is backed off relative to the earlier loud pass.
    ]
    /// Audio transport for file/turn playback. WebSocket remains the default
    /// unless --usb-map is supplied, in which case USB is the assumed test path.
    var transport: AudioTransportMode = .ws
    var transportWasSet: Bool = false
    var usbMapPath: String? = nil
}

func parseArgs() -> Args {
    var args = Args()
    var i = 1
    let argv = CommandLine.arguments
    while i < argv.count {
        let a = argv[i]
        switch a {
        case "--port":
            i += 1
            guard i < argv.count, let p = UInt16(argv[i]) else {
                fputs("error: --port requires a number\n", stderr); exit(2)
            }
            args.port = p
        case "--sine":
            args.sine = true
            // Optional next arg = solo duck. If next is a known DuckID, eat it.
            if i + 1 < argv.count, let d = DuckID.parse(argv[i + 1]) {
                args.soloDuck = d
                i += 1
            }
        case "--duck-map":
            i += 1
            guard i < argv.count else {
                fputs("error: --duck-map requires a path\n", stderr); exit(2)
            }
            args.duckMapPath = argv[i]
        case "--no-duck-map":
            args.noDuckMap = true
        case "--mode1":
            args.mode1 = true
        case "--input-device":
            i += 1
            guard i < argv.count else {
                fputs("error: --input-device requires a name substring\n", stderr)
                exit(2)
            }
            args.inputDeviceMatch = argv[i]
        case "--list-inputs":
            args.listInputs = true
        case "--play":
            i += 1
            guard i < argv.count else {
                fputs("error: --play requires a file path\n", stderr); exit(2)
            }
            let path = argv[i]
            // Optional next arg = target duck (default D1). Repeatable:
            // --play a.wav D1 --play b.wav D2 drives both at once.
            var duck = DuckID.D1
            if i + 1 < argv.count, let d = DuckID.parse(argv[i + 1]) {
                duck = d
                i += 1
            }
            args.plays.append((path: path, duck: duck))
        case "--loop":
            args.loop = true
        case "--wait-trigger":
            args.waitTrigger = true
        case "--playlist-dir":
            i += 1
            guard i < argv.count else {
                fputs("error: --playlist-dir requires a directory\n", stderr)
                exit(2)
            }
            args.playlistDir = argv[i]
        case "--turn-manifest":
            i += 1
            guard i < argv.count else {
                fputs("error: --turn-manifest requires a manifest JSON path\n", stderr)
                exit(2)
            }
            args.turnManifestPath = argv[i]
        case "--usb-map":
            i += 1
            guard i < argv.count else {
                fputs("error: --usb-map requires a path\n", stderr)
                exit(2)
            }
            args.usbMapPath = argv[i]
        case "--transport":
            i += 1
            guard i < argv.count, let mode = AudioTransportMode.parse(argv[i]) else {
                fputs("error: --transport requires ws, usb, or auto\n", stderr)
                exit(2)
            }
            args.transport = mode
            args.transportWasSet = true
        case "--duck-alias":
            i += 1
            guard i < argv.count else {
                fputs("error: --duck-alias requires FROM=TO, e.g. D3=D1\n", stderr)
                exit(2)
            }
            let parts = argv[i].split(separator: "=", maxSplits: 1)
            guard parts.count == 2,
                  let from = DuckID.parse(String(parts[0])),
                  let to = DuckID.parse(String(parts[1])) else {
                fputs("error: --duck-alias must look like D3=D1\n", stderr)
                exit(2)
            }
            args.duckAliases[from] = to
        case "--duck-gain":
            i += 1
            guard i < argv.count else {
                fputs("error: --duck-gain requires DUCK=GAIN, e.g. D4=2.6\n", stderr)
                exit(2)
            }
            applyDuckGainSpec(argv[i], to: &args.duckGains)
        case "-h", "--help":
            printHelp(); exit(0)
        default:
            fputs("error: unknown arg \(a)\n", stderr)
            printHelp(); exit(2)
        }
        i += 1
    }
    if args.usbMapPath != nil && !args.transportWasSet {
        args.transport = .usb
    }
    if args.duckMapPath != nil && args.noDuckMap {
        fputs("error: --duck-map and --no-duck-map are mutually exclusive\n", stderr)
        exit(2)
    }
    if args.transport == .usb && args.usbMapPath == nil {
        fputs("error: --transport usb requires --usb-map FILE\n", stderr)
        exit(2)
    }
    if args.playlistDir != nil && !args.plays.isEmpty {
        fputs("error: --playlist-dir and --play are mutually exclusive\n", stderr)
        exit(2)
    }
    if args.turnManifestPath != nil &&
       (args.playlistDir != nil || !args.plays.isEmpty) {
        fputs("error: --turn-manifest is mutually exclusive with --playlist-dir / --play\n",
              stderr)
        exit(2)
    }
    return args
}

func printHelp() {
    let help = """
    Boy Band — Stage server

    Usage:
      BoyBandStage [--port N] [--sine [DUCKID]]
                   [--duck-map FILE.json | --no-duck-map]
                   [--mode1 [--input-device SUBSTR]]
                   [--play FILE [DUCKID] [--loop]]
                   [--list-inputs]

    Options:
      --port N             Listen port (default 3334)
      --sine               Stream a steady sine to every connected duck
      --sine DUCKID        Solo one duck (D1..D4); others stay silent
      --duck-map FILE      Path to MAC→slot JSON map (used by /ws/duck)
      --no-duck-map        Disable /ws/duck; only test path /duck/{ID} works
      --mode1              Mode 1: read 4ch input from CoreAudio, route to ducks
      --input-device STR   Substring of input device name (default "BlackHole")
      --play FILE [DUCKID] Stream an audio file (wav/aiff/mp3/m4a) to one duck
                           (default D1). Resamples to 16k/mono/int16, paced.
      --playlist-dir DIR   Preload NAME_partNN_DX.wav chunks. /next and /prev
                           switch cues without restarting Stage.
      --turn-manifest FILE Preload gen-play-stems.py manifest; /play streams
                           one speaker utterance at a time.
      --duck-alias FROM=TO Route one manifest duck to another, e.g. D3=D1.
      --duck-gain DUCK=N   Per-duck digital gain, repeatable. DUCK may be
                           D1..D4 or ALL. Example: --duck-gain D4=3.0
      --usb-map FILE       Open ducks over USB Serial/JTAG from local map.
      --transport MODE     ws, usb, or auto for file/turn playback.
      --loop               With --play: loop the file instead of one pass
      --list-inputs        Print available input devices and exit
      -h, --help           Show this help

    Routes:
      /ws/duck    + X-Duck-Id: <MAC>     real firmware path (needs duck-map)
      /duck/{ID}                          test/dev shortcut (no map needed)

    Default duck-map search order: ./duck-map.local.json,
    then <repo>/boyband/duck-map.local.json.
    """
    print(help)
}

func applyDuckGainSpec(_ spec: String, to gains: inout [DuckID: Double]) {
    let parts = spec.split(separator: "=", maxSplits: 1)
    guard parts.count == 2, let gain = Double(parts[1]), gain >= 0.0, gain <= 8.0 else {
        fputs("error: --duck-gain must look like D4=2.6, gain range 0...8\n", stderr)
        exit(2)
    }
    let key = parts[0].uppercased()
    if key == "ALL" {
        for duck in DuckID.allCases { gains[duck] = gain }
        return
    }
    guard let duck = DuckID.parse(key) else {
        fputs("error: --duck-gain duck must be D1..D4 or ALL\n", stderr)
        exit(2)
    }
    gains[duck] = gain
}

/// Try the default map locations in order. Returns nil if none exist.
func defaultDuckMapPath() -> String? {
    let candidates = [
        "duck-map.local.json",
        "../duck-map.local.json",
        // Common case: invoked from inside boyband/stage/
        "../boyband/duck-map.local.json",
    ]
    let fm = FileManager.default
    for c in candidates {
        if fm.fileExists(atPath: c) { return c }
    }
    return nil
}

// MARK: - Logging

func log(_ s: String) {
    let ts = ISO8601DateFormatter().string(from: Date())
    print("[\(ts)] \(s)")
}

// MARK: - Main

let args = parseArgs()

// --list-inputs: print devices and exit. Does not start the server.
if args.listInputs {
    let devices = DAWInput.listInputDevices()
    if devices.isEmpty {
        print("(no input devices found)")
    } else {
        print("Available input devices:")
        for d in devices {
            print(String(format: "  %3dch  %@", d.channels, d.name))
        }
    }
    exit(0)
}

var sineGen: SineGenerator?  // set after server starts
var dawInput: DAWInput?      // set if Mode 1 enabled
var filePlayers: [FilePlayer] = []  // one per --play pair

struct LoadedTrack: @unchecked Sendable {
    let player: FilePlayer
    let duck: DuckID
    let path: String
    let durationSec: Double
}

struct LoadedCue: @unchecked Sendable {
    let part: Int
    let name: String
    let tracks: [LoadedTrack]
    let durationSec: Double
}

struct TurnManifest: Decodable {
    let gapMs: Int?
    let turns: [TurnManifestTurn]

    enum CodingKeys: String, CodingKey {
        case gapMs = "gap_ms"
        case turns
    }
}

struct TurnManifestTurn: Decodable {
    let index: Int
    let speaker: String
    let duck: String
    let ducks: [String]?
    let text: String?
    let clip: String
    let clips: [String: String]?
    let durationSec: Double?

    enum CodingKeys: String, CodingKey {
        case index
        case speaker
        case duck
        case ducks
        case text
        case clip
        case clips
        case durationSec = "duration_sec"
    }
}

struct LoadedUtteranceTrack: @unchecked Sendable {
    let sourceDuck: DuckID
    let duck: DuckID
    let path: String
    let player: FilePlayer
    let durationSec: Double
}

struct LoadedUtterance: @unchecked Sendable {
    let index: Int
    let speaker: String
    let text: String
    let tracks: [LoadedUtteranceTrack]
    let durationSec: Double

    var sourceDuck: DuckID { tracks[0].sourceDuck }
    var duck: DuckID { tracks[0].duck }

    var alias: String {
        tracks.map { track in
            track.sourceDuck == track.duck
                ? track.duck.rawValue
                : "\(track.sourceDuck.rawValue)→\(track.duck.rawValue)"
        }.joined(separator: "+")
    }

    var targetLabels: String {
        tracks.map { label($0.duck) }.joined(separator: ", ")
    }
}

struct QAHelperResult: Decodable {
    let question: String
    let lines: [QAHelperLine]
}

struct QAHelperLine: Decodable {
    let duck: String
    let speaker: String
    let text: String
    let path: String
    let durationSec: Double

    enum CodingKeys: String, CodingKey {
        case duck
        case speaker
        case text
        case path
        case durationSec = "duration_sec"
    }
}

final class PlaylistState: @unchecked Sendable {
    private let lock = NSLock()
    private var index: Int = 0
    private var playing: Bool = false
    private var generation: Int = 0
    private var remainingTracks: Int = 0
    private var startedAt: Date?

    func currentIndex() -> Int {
        lock.lock(); defer { lock.unlock() }
        return index
    }

    func snapshot() -> (index: Int, playing: Bool, generation: Int, startedAt: Date?) {
        lock.lock(); defer { lock.unlock() }
        return (index, playing, generation, startedAt)
    }

    func advance(delta: Int, maxIndex: Int) -> Int {
        lock.lock(); defer { lock.unlock() }
        index = min(max(index + delta, 0), maxIndex)
        playing = false
        remainingTracks = 0
        startedAt = nil
        generation += 1
        return index
    }

    func jump(to newIndex: Int, maxIndex: Int) -> Int {
        lock.lock(); defer { lock.unlock() }
        index = min(max(newIndex, 0), maxIndex)
        playing = false
        remainingTracks = 0
        startedAt = nil
        generation += 1
        return index
    }

    func start(trackCount: Int) -> Int {
        lock.lock(); defer { lock.unlock() }
        generation += 1
        remainingTracks = trackCount
        playing = trackCount > 0
        startedAt = playing ? Date() : nil
        return generation
    }

    func stop() {
        lock.lock(); defer { lock.unlock() }
        generation += 1
        remainingTracks = 0
        playing = false
        startedAt = nil
    }

    func finish(generation expectedGeneration: Int) -> Bool {
        lock.lock(); defer { lock.unlock() }
        guard generation == expectedGeneration else { return false }
        remainingTracks = max(remainingTracks - 1, 0)
        guard remainingTracks == 0 else { return false }
        playing = false
        startedAt = nil
        return true
    }
}

final class DuckGainStore: @unchecked Sendable {
    private let lock = NSLock()
    private var balances: [DuckID: Double]
    private var global: Double

    init(initial: [DuckID: Double]) {
        self.balances = initial
        self.global = 1.0
    }

    func get(_ duck: DuckID) -> Double {
        lock.lock(); defer { lock.unlock() }
        return global * (balances[duck] ?? 1.0)
    }

    func balance(_ duck: DuckID) -> Double {
        lock.lock(); defer { lock.unlock() }
        return balances[duck] ?? 1.0
    }

    func setBalance(_ duck: DuckID, _ value: Double) {
        lock.lock()
        balances[duck] = value
        lock.unlock()
    }

    func setGlobal(_ value: Double) {
        lock.lock()
        global = value
        lock.unlock()
    }

    func snapshot() -> (global: Double, balances: [DuckID: Double]) {
        lock.lock(); defer { lock.unlock() }
        return (global, balances)
    }
}

final class RecoveryMonitor: @unchecked Sendable {
    private let lock = NSLock()
    private var timer: DispatchSourceTimer?

    func replace(with newTimer: DispatchSourceTimer) {
        lock.lock()
        let oldTimer = timer
        timer = newTimer
        lock.unlock()
        oldTimer?.cancel()
        newTimer.resume()
    }

    func cancel() {
        lock.lock()
        let oldTimer = timer
        timer = nil
        lock.unlock()
        oldTimer?.cancel()
    }
}

final class DuckStatsTracker: @unchecked Sendable {
    struct Snapshot {
        let rxBps: Int
        let stalledSamples: Int
        let ageMs: Double
    }

    private struct Entry {
        var rxBps: Int = 0
        var stalledSamples: Int = 0
        var updatedAt: Date = .distantPast
    }

    private let lock = NSLock()
    private var entries: [DuckID: Entry] = [:]
    private let expectedRxBps = 32_000
    private let stalledRxBps = 12_000

    func reset(_ duck: DuckID) {
        lock.lock()
        entries[duck] = Entry()
        lock.unlock()
    }

    func noteText(duck: DuckID, text: String) {
        guard text.contains("\"type\":\"duck_stats\""),
              let data = text.data(using: .utf8),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let rx = json["rx_bps"] as? NSNumber else {
            return
        }

        let rxBps = rx.intValue
        lock.lock()
        var entry = entries[duck] ?? Entry()
        entry.rxBps = rxBps
        entry.updatedAt = Date()
        if rxBps < stalledRxBps {
            entry.stalledSamples += 1
        } else if rxBps > expectedRxBps / 2 {
            entry.stalledSamples = 0
        }
        entries[duck] = entry
        lock.unlock()
    }

    func stalledDucks(targets: [DuckID], playbackStartedAt: Date?,
                      minElapsedSec: TimeInterval = 4.0) -> [DuckID] {
        guard let playbackStartedAt,
              Date().timeIntervalSince(playbackStartedAt) >= minElapsedSec else {
            return []
        }

        lock.lock()
        let now = Date()
        let stalled = targets.filter { duck in
            guard let entry = entries[duck] else { return false }
            let ageMs = now.timeIntervalSince(entry.updatedAt) * 1000
            return ageMs <= 2_500 && entry.stalledSamples >= 2
        }
        lock.unlock()
        return stalled
    }
}

func jsonEscape(_ s: String) -> String {
    var out = ""
    for ch in s {
        switch ch {
        case "\\": out += "\\\\"
        case "\"": out += "\\\""
        case "\n": out += "\\n"
        case "\r": out += "\\r"
        case "\t": out += "\\t"
        default: out.append(ch)
        }
    }
    return out
}

func previewWords(_ s: String, maxWords: Int = 5) -> String {
    s.split(whereSeparator: { $0.isWhitespace })
        .prefix(maxWords)
        .joined(separator: " ")
}

// Resolve duck-map FIRST so the connect/disconnect logs can show names.
let duckMap: DuckMap? = {
    if args.noDuckMap { return nil }
    let path = args.duckMapPath ?? defaultDuckMapPath()
    guard let path else {
        log("duck-map    not found (production /ws/duck path disabled). " +
            "Use --duck-map FILE or --no-duck-map to silence this warning.")
        return nil
    }
    guard let map = DuckMap.load(from: path) else {
        fputs("fatal: --duck-map \(path) could not be loaded\n", stderr)
        exit(1)
    }
    let entries = map.allEntries
    log("duck-map    loaded \(path) — \(entries.count) entries")
    for e in entries {
        let nm = e.name.map { " \"\($0)\"" } ?? ""
        log("  \(e.duck.rawValue)\(nm) ← \(e.mac)")
    }
    return map
}()

let usbMap: USBDuckMap? = {
    guard let path = args.usbMapPath else { return nil }
    guard let map = USBDuckMap.load(from: path) else {
        fputs("fatal: --usb-map \(path) could not be loaded\n", stderr)
        exit(1)
    }
    log("usb-map     loaded \(path) — \(map.allEntries.count) entries")
    for e in map.allEntries {
        let nm = e.name.map { " \"\($0)\"" } ?? ""
        let dev = e.currentDevice ?? "(auto)"
        log("  \(e.duck.rawValue)\(nm) ← \(e.usbSerial ?? "no-serial") \(dev)")
    }
    return map
}()

// Label a connection as "D2 (Pekin)" when a name is known, else just "D2".
func label(_ duck: DuckID) -> String {
    if let n = duckMap?.name(for: duck) { return "\(duck.rawValue) (\(n))" }
    if let n = usbMap?.name(for: duck) { return "\(duck.rawValue) (\(n))" }
    return duck.rawValue
}

let duckGains = DuckGainStore(initial: args.duckGains)

let gainSummary = DuckID.allCases
    .map { "\(label($0))=\(String(format: "%.2f", duckGains.balance($0)))x" }
    .joined(separator: ", ")
log("gain        global=1.00x balance \(gainSummary)")

let duckStats = DuckStatsTracker()

let callbacks = StageCallbacks(
    onConnect: { conn in
        duckStats.reset(conn.duck)
        log("connect    \(label(conn.duck))  id=\(conn.id.uuidString.prefix(8))")
    },
    onDisconnect: { conn in
        duckStats.reset(conn.duck)
        log("disconnect \(label(conn.duck))  id=\(conn.id.uuidString.prefix(8))")
    },
    onText: { conn, text in
        duckStats.noteText(duck: conn.duck, text: text)
        log("text       \(label(conn.duck))  \(text)")
    },
    onBinary: { _, _ in
        // Duck mic frames are dropped — we use the Mac mic in Mode 2.
    }
)

let server = StageServer(port: args.port, duckMap: duckMap, callbacks: callbacks)

do {
    try server.start()
} catch {
    fputs("fatal: cannot bind port \(args.port): \(error)\n", stderr)
    exit(1)
}

if duckMap != nil {
    log("listening on ws://0.0.0.0:\(args.port)/ws/duck (prod) " +
        "and /duck/{D1..D4} (test)")
} else {
    log("listening on ws://0.0.0.0:\(args.port)/duck/{D1..D4} (test only)")
}

let usbStage: USBStage? = {
    guard let usbMap else { return nil }
    let stage = USBStage(map: usbMap, logger: log)
    stage.start()
    log("transport  \(args.transport.rawValue)")
    return stage
}()

@Sendable func transportIsConnected(_ duck: DuckID) -> Bool {
    switch args.transport {
    case .ws:
        return server.connection(for: duck) != nil
    case .usb:
        return usbStage?.isConnected(duck) ?? false
    case .auto:
        return (usbStage?.isConnected(duck) ?? false) ||
               server.connection(for: duck) != nil
    }
}

@Sendable func transportSendPCM(_ duck: DuckID, _ pcm: Data) {
    switch args.transport {
    case .ws:
        server.connection(for: duck)?.sendPCM(pcm)
    case .usb:
        usbStage?.sendPCM(duck, pcm)
    case .auto:
        if usbStage?.isConnected(duck) == true {
            usbStage?.sendPCM(duck, pcm)
        } else {
            server.connection(for: duck)?.sendPCM(pcm)
        }
    }
}

@Sendable func transportInFlightBytes(_ duck: DuckID) -> Int {
    switch args.transport {
    case .ws:
        return server.connection(for: duck)?.stats().inFlightBytes ?? 0
    case .usb:
        return usbStage?.stats(for: duck)?.inFlightBytes ?? 0
    case .auto:
        if usbStage?.isConnected(duck) == true {
            return usbStage?.stats(for: duck)?.inFlightBytes ?? 0
        }
        return server.connection(for: duck)?.stats().inFlightBytes ?? 0
    }
}

@discardableResult
@Sendable func transportKick(_ duck: DuckID) -> Bool {
    switch args.transport {
    case .ws:
        return server.kick(duck)
    case .usb:
        return usbStage?.kick(duck) ?? false
    case .auto:
        if usbStage?.isConnected(duck) == true {
            return usbStage?.kick(duck) ?? false
        }
        return server.kick(duck)
    }
}

@Sendable func transportReset(_ duck: DuckID) {
    if args.transport == .usb || args.transport == .auto {
        usbStage?.reset(duck)
    }
}

@Sendable func transportStatusReport() -> String {
    switch args.transport {
    case .ws:
        return server.statusReport()
    case .usb:
        return usbStage?.statusReport() ?? "connected: none\n"
    case .auto:
        if let usbStage, !usbStage.statusReport().hasPrefix("connected: none") {
            return usbStage.statusReport()
        }
        return server.statusReport()
    }
}

@Sendable func transportHealthReport() -> String {
    switch args.transport {
    case .ws:
        return server.healthReport()
    case .usb:
        return usbStage?.healthReport() ?? "connected: none\n"
    case .auto:
        if let usbStage, !usbStage.healthReport().hasPrefix("connected: none") {
            return usbStage.healthReport()
        }
        return server.healthReport()
    }
}

func duckGain(_ duck: DuckID) -> Double {
    duckGains.get(duck)
}

func gainJSON() -> String {
    let snapshot = duckGains.snapshot()
    let items = DuckID.allCases.map { duck in
        let name = label(duck)
        let balance = snapshot.balances[duck] ?? 1.0
        let effective = snapshot.global * balance
        return """
        "\(duck.rawValue)":{"name":"\(jsonEscape(name))","balance":\(String(format: "%.3f", balance)),"effective":\(String(format: "%.3f", effective))}
        """
    }.joined(separator: ",")
    return "{\"global\":\(String(format: "%.3f", snapshot.global)),\"ducks\":{\(items)}}\n"
}

func handleGainControl(_ command: String) -> String {
    guard command.hasPrefix("gain:") else { return gainJSON() }
    let raw = String(command.dropFirst("gain:".count))
    let parts = raw.split(separator: "=", maxSplits: 1)
    guard parts.count == 2,
          let gain = Double(parts[1]),
          gain >= 0.0,
          gain <= 8.0 else {
        return "{\"error\":\"gain must be 0...8\"}\n"
    }
    let key = parts[0].uppercased()
    if key == "GLOBAL" {
        duckGains.setGlobal(gain)
        log("gain        global=\(String(format: "%.2f", gain))x")
        return gainJSON()
    }
    if key == "ALL" {
        for duck in DuckID.allCases { duckGains.setBalance(duck, gain) }
        log("gain        balance ALL=\(String(format: "%.2f", gain))x")
        return gainJSON()
    }
    guard let duck = DuckID.parse(key) else {
        return "{\"error\":\"target must be D1..D4, ALL, or GLOBAL\"}\n"
    }
    duckGains.setBalance(duck, gain)
    log("gain        balance \(label(duck))=\(String(format: "%.2f", gain))x " +
        "effective=\(String(format: "%.2f", duckGains.get(duck)))x")
    return gainJSON()
}

func makeFilePlayer(duck: DuckID, loop: Bool) -> FilePlayer {
    FilePlayer(duck: duck,
               loop: loop,
               gainProvider: duckGain,
               isConnected: transportIsConnected,
               sendPCM: transportSendPCM)
}

func runQAHelper(question: String) throws -> QAHelperResult {
    let stageDir = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
    let boybandDir = stageDir.deletingLastPathComponent()
    let python = boybandDir.appendingPathComponent(".venv/bin/python").path
    let script = boybandDir.appendingPathComponent("scripts/qa-eleven.py").path
    let executable = FileManager.default.fileExists(atPath: python) ? python : "/usr/bin/python3"

    let p = Process()
    p.executableURL = URL(fileURLWithPath: executable)
    p.arguments = [script, question]
    p.currentDirectoryURL = boybandDir.deletingLastPathComponent()
    let outPipe = Pipe()
    let errPipe = Pipe()
    p.standardOutput = outPipe
    p.standardError = errPipe
    try p.run()
    p.waitUntilExit()

    let outData = outPipe.fileHandleForReading.readDataToEndOfFile()
    let errData = errPipe.fileHandleForReading.readDataToEndOfFile()
    if p.terminationStatus != 0 {
        let errText = String(data: errData, encoding: .utf8) ?? "unknown error"
        throw NSError(domain: "QAHelper", code: Int(p.terminationStatus),
                      userInfo: [NSLocalizedDescriptionKey: errText.trimmingCharacters(in: .whitespacesAndNewlines)])
    }
    return try JSONDecoder().decode(QAHelperResult.self, from: outData)
}

if args.sine {
    let gen = SineGenerator(server: server)
    gen.start(solo: args.soloDuck)
    sineGen = gen
    if let solo = args.soloDuck {
        log("sine        solo=\(solo.rawValue) (others silent)")
    } else {
        log("sine        broadcasting to all connected ducks")
    }
}

if args.mode1 {
    if args.sine {
        fputs("error: --mode1 and --sine are mutually exclusive\n", stderr)
        exit(2)
    }
    guard let devID = DAWInput.findDevice(matching: args.inputDeviceMatch,
                                          minChannels: 4) else {
        fputs("fatal: no input device matching '\(args.inputDeviceMatch)' with ≥4 channels\n",
              stderr)
        fputs("       run with --list-inputs to see what's available\n", stderr)
        exit(1)
    }
    let input = DAWInput(server: server)
    do {
        try input.start(deviceID: devID)
        dawInput = input
        log("mode1       reading 4ch input matching '\(args.inputDeviceMatch)' → D1..D4")
    } catch {
        fputs("fatal: mode1 start failed: \(error.localizedDescription)\n", stderr)
        exit(1)
    }
}

if let turnManifestPath = args.turnManifestPath {
    if args.sine || args.mode1 {
        fputs("error: --turn-manifest is mutually exclusive with --sine / --mode1\n",
              stderr)
        exit(2)
    }

    let manifestURL = URL(fileURLWithPath: turnManifestPath)
    let manifestBaseURL = manifestURL.deletingLastPathComponent()
    let manifest: TurnManifest
    do {
        let data = try Data(contentsOf: manifestURL)
        manifest = try JSONDecoder().decode(TurnManifest.self, from: data)
    } catch {
        fputs("fatal: --turn-manifest \(turnManifestPath) failed: \(error.localizedDescription)\n",
              stderr)
        exit(1)
    }
    if manifest.turns.isEmpty {
        fputs("fatal: --turn-manifest \(turnManifestPath) has no turns\n", stderr)
        exit(1)
    }

    let utterances: [LoadedUtterance] = manifest.turns.map { turn in
        let rawDucks = (turn.ducks?.isEmpty == false) ? turn.ducks! : [turn.duck]
        var tracks: [LoadedUtteranceTrack] = []
        for rawDuck in rawDucks {
            guard let sourceDuck = DuckID.parse(rawDuck) else {
                fputs("fatal: manifest turn \(turn.index) has unknown duck \(rawDuck)\n",
                      stderr)
                exit(1)
            }
            let targetDuck = args.duckAliases[sourceDuck] ?? sourceDuck
            let clip = turn.clips?[sourceDuck.rawValue] ?? turn.clip
            let clipURL = clip.hasPrefix("/")
                ? URL(fileURLWithPath: clip)
                : manifestBaseURL.appendingPathComponent(clip)
            let player = makeFilePlayer(duck: targetDuck, loop: false)
            let durationSec: Double
            do {
                durationSec = try player.load(path: clipURL.path)
            } catch {
                fputs("fatal: turn \(turn.index) clip \(clipURL.path) failed: \(error.localizedDescription)\n",
                      stderr)
                exit(1)
            }
            tracks.append(LoadedUtteranceTrack(sourceDuck: sourceDuck,
                                               duck: targetDuck,
                                               path: clipURL.path,
                                               player: player,
                                               durationSec: durationSec))
        }
        let durationSec = tracks.map(\.durationSec).max() ?? turn.durationSec ?? 0.0
        let aliasNote = tracks.map { track in
            track.sourceDuck == track.duck
                ? track.duck.rawValue
                : "\(track.sourceDuck.rawValue)→\(track.duck.rawValue)"
        }.joined(separator: "+")
        let clipNames = tracks
            .map { ($0.path as NSString).lastPathComponent }
            .joined(separator: ",")
        log(String(format: "turns      %02d %@ %@ %.2fs %@",
                   turn.index, turn.speaker, aliasNote, durationSec, clipNames))
        return LoadedUtterance(index: turn.index,
                               speaker: turn.speaker,
                               text: turn.text ?? "",
                               tracks: tracks,
                               durationSec: durationSec)
    }

    filePlayers = utterances.flatMap { $0.tracks.map(\.player) }
    let turnState = PlaylistState()
    let gapSec = Double(manifest.gapMs ?? 300) / 1000.0
    let qaState = PlaylistState()
    let qaLock = NSLock()
    var qaUtterances: [LoadedUtterance] = []
    var qaQuestion: String = ""

    @Sendable func turnLine() -> String {
        let i = turnState.currentIndex()
        let u = utterances[i]
        return "turn \(i + 1)/\(utterances.count): \(u.speaker) \(u.alias)\n"
    }

    @Sendable func stopAllTurns() {
        for u in utterances {
            for track in u.tracks { track.player.stop() }
        }
        for duck in Set(utterances.flatMap { $0.tracks.map(\.duck) }) {
            transportReset(duck)
        }
        turnState.stop()
    }

    @Sendable func stopQA(clear: Bool = false) {
        qaLock.lock()
        let snapshot = qaUtterances
        if clear {
            qaUtterances.removeAll()
            qaQuestion = ""
        }
        qaLock.unlock()
        for u in snapshot {
            for track in u.tracks { track.player.stop() }
        }
        for duck in Set(snapshot.flatMap { $0.tracks.map(\.duck) }) {
            transportReset(duck)
        }
        qaState.stop()
    }

    @Sendable func qaSnapshotUtterances() -> (question: String, utterances: [LoadedUtterance]) {
        qaLock.lock(); defer { qaLock.unlock() }
        return (qaQuestion, qaUtterances)
    }

    @Sendable func finishQATurnAfterDrain(_ utterance: LoadedUtterance,
                                          track: LoadedUtteranceTrack,
                                          generation: Int,
                                          startedWaitingAt: Date = Date()) {
        let timeoutSec = 4.0
        let inFlightBytes = transportInFlightBytes(track.duck)
        if inFlightBytes > 0 {
            let waited = Date().timeIntervalSince(startedWaitingAt)
            if waited >= timeoutSec {
                log("qa         \(String(format: "%02d", utterance.index)) " +
                    "\(utterance.speaker) drain timed out " +
                    "(\(StageServer.formatBytesForLog(inFlightBytes)) in flight); kicking \(label(track.duck))")
                _ = transportKick(track.duck)
                qaState.stop()
                return
            }
            DispatchQueue.global().asyncAfter(deadline: .now() + .milliseconds(100)) {
                finishQATurnAfterDrain(utterance,
                                       track: track,
                                       generation: generation,
                                       startedWaitingAt: startedWaitingAt)
            }
            return
        }

        log(String(format: "qa         %02d %@ %@ finished",
                   utterance.index, utterance.speaker, track.duck.rawValue))
        guard qaState.finish(generation: generation) else { return }
        let (_, currentQA) = qaSnapshotUtterances()
        let finishedIndex = qaState.currentIndex()
        guard finishedIndex < currentQA.count - 1 else {
            log("qa         complete")
            return
        }
        DispatchQueue.global().asyncAfter(deadline: .now() + gapSec) {
            let snapshot = qaState.snapshot()
            guard snapshot.generation == generation else { return }
            let nextIndex = qaState.advance(delta: 1, maxIndex: currentQA.count - 1)
            triggerQATurn(currentQA[nextIndex])
        }
    }

    @Sendable func triggerQATurn(_ utterance: LoadedUtterance) {
        let targets = utterance.tracks.map(\.duck)
        let present = targets.filter { transportIsConnected($0) }.count
        guard present == targets.count else {
            qaState.stop()
            log(String(format: "qa         paused %02d %@ → %@ (%d/%d connected)",
                       utterance.index, utterance.speaker, utterance.targetLabels,
                       present, targets.count))
            return
        }
        log(String(format: "qa         ▶ %02d %@ → %@",
                   utterance.index, utterance.speaker, utterance.targetLabels))
        for duck in targets { duckStats.reset(duck) }
        for duck in targets { transportReset(duck) }
        let generation = qaState.start(trackCount: utterance.tracks.count)
        for track in utterance.tracks {
            track.player.rewind()
            track.player.start(sharedClock: utterance.tracks.count > 1,
                               onDone: {
                                   finishQATurnAfterDrain(utterance,
                                                          track: track,
                                                          generation: generation)
                               })
        }
    }

    @Sendable func finishTurnAfterDrain(_ utterance: LoadedUtterance,
                                        track: LoadedUtteranceTrack,
                                        generation: Int,
                                        startedWaitingAt: Date = Date()) {
        let timeoutSec = 4.0
        let inFlightBytes = transportInFlightBytes(track.duck)
        if inFlightBytes > 0 {
                let waited = Date().timeIntervalSince(startedWaitingAt)
                if waited >= timeoutSec {
                    log("turns      \(String(format: "%02d", utterance.index)) " +
                        "\(utterance.speaker) drain timed out " +
                        "(\(StageServer.formatBytesForLog(inFlightBytes)) in flight); kicking \(label(track.duck))")
                    _ = transportKick(track.duck)
                    turnState.stop()
                    return
                } else {
                    DispatchQueue.global().asyncAfter(deadline: .now() + .milliseconds(100)) {
                        finishTurnAfterDrain(utterance,
                                             track: track,
                                             generation: generation,
                                             startedWaitingAt: startedWaitingAt)
                    }
                    return
            }
        }

        log(String(format: "turns      %02d %@ %@ finished",
                   utterance.index, utterance.speaker, track.duck.rawValue))
        guard turnState.finish(generation: generation) else {
            return
        }
        let finishedIndex = turnState.currentIndex()
        guard finishedIndex < utterances.count - 1 else {
            log("turns      complete")
            return
        }
        DispatchQueue.global().asyncAfter(deadline: .now() + gapSec) {
            let snapshot = turnState.snapshot()
            guard snapshot.generation == generation else { return }
            let nextIndex = turnState.advance(delta: 1,
                                              maxIndex: utterances.count - 1)
            triggerTurn(utterances[nextIndex])
        }
    }

    @Sendable func triggerTurn(_ utterance: LoadedUtterance) {
        let i = turnState.currentIndex()
        let targets = utterance.tracks.map(\.duck)
        let present = targets.filter { transportIsConnected($0) }.count
        guard present == targets.count else {
            turnState.stop()
            log(String(format: "turns      paused %02d/%02d %@ → %@ (%d/%d connected)",
                       i + 1, utterances.count, utterance.speaker,
                       utterance.targetLabels, present, targets.count))
            return
        }
        log(String(format: "turns      ▶ %02d/%02d %@ → %@ (%d/%d connected)",
                   i + 1, utterances.count, utterance.speaker,
                   utterance.targetLabels, present, targets.count))
        for duck in targets { duckStats.reset(duck) }
        for duck in targets { transportReset(duck) }
        let generation = turnState.start(trackCount: utterance.tracks.count)
        for track in utterance.tracks {
            track.player.rewind()
            track.player.start(sharedClock: utterance.tracks.count > 1,
                               onDone: {
                                   finishTurnAfterDrain(utterance,
                                                        track: track,
                                                        generation: generation)
                               })
        }
    }

    @Sendable func stateJSON() -> String {
        let qaSnapshot = qaState.snapshot()
        let (question, currentQA) = qaSnapshotUtterances()
        if !currentQA.isEmpty {
            let idx = min(max(qaSnapshot.index, 0), currentQA.count - 1)
            let u = currentQA[idx]
            let elapsedSec = qaSnapshot.startedAt.map { min(Date().timeIntervalSince($0),
                                                            u.durationSec) } ?? 0.0
            let name = String(format: "Q&A %02d %@", u.index, u.speaker)
            let items = currentQA.enumerated().map { offset, item in
                """
                {"index":\(offset),"line":\(item.index),"speaker":"\(jsonEscape(item.speaker))","duck":"\(item.duck.rawValue)","sourceDuck":"\(item.sourceDuck.rawValue)","alias":"\(jsonEscape(item.alias))","preview":"\(jsonEscape(previewWords(item.text)))"}
                """
            }.joined(separator: ",")
            return """
            {"cue":{"index":\(idx),"count":\(currentQA.count),"name":"\(jsonEscape(name))","durationSec":\(String(format: "%.3f", u.durationSec)),"generation":\(qaSnapshot.generation),"elapsedSec":\(String(format: "%.3f", elapsedSec))},"playing":\(qaSnapshot.playing ? "true" : "false"),"turn":{"speaker":"\(jsonEscape(u.speaker))","duck":"\(u.duck.rawValue)","sourceDuck":"\(u.sourceDuck.rawValue)","alias":"\(jsonEscape(u.alias))","text":"\(jsonEscape(u.text))","question":"\(jsonEscape(question))"},"turns":[\(items)],"status":"\(jsonEscape(transportStatusReport()))","health":"\(jsonEscape(transportHealthReport()))"}

            """
        }

        let snapshot = turnState.snapshot()
        let u = utterances[snapshot.index]
        let elapsedSec = snapshot.startedAt.map { min(Date().timeIntervalSince($0),
                                                      u.durationSec) } ?? 0.0
        let name = String(format: "line%02d %@", u.index, u.speaker)
        let turnItems = utterances.enumerated().map { offset, item in
            return """
            {"index":\(offset),"line":\(item.index),"speaker":"\(jsonEscape(item.speaker))","duck":"\(item.duck.rawValue)","sourceDuck":"\(item.sourceDuck.rawValue)","alias":"\(jsonEscape(item.alias))","preview":"\(jsonEscape(previewWords(item.text)))"}
            """
        }.joined(separator: ",")
        return """
        {"cue":{"index":\(snapshot.index),"count":\(utterances.count),"name":"\(jsonEscape(name))","durationSec":\(String(format: "%.3f", u.durationSec)),"generation":\(snapshot.generation),"elapsedSec":\(String(format: "%.3f", elapsedSec))},"playing":\(snapshot.playing ? "true" : "false"),"turn":{"speaker":"\(jsonEscape(u.speaker))","duck":"\(u.duck.rawValue)","sourceDuck":"\(u.sourceDuck.rawValue)","alias":"\(jsonEscape(u.alias))","text":"\(jsonEscape(u.text))"},"turns":[\(turnItems)],"status":"\(jsonEscape(transportStatusReport()))","health":"\(jsonEscape(transportHealthReport()))"}

        """
    }

    server.onControl = { cmd in
        switch cmd {
        case "play":
            stopQA(clear: true)
            stopAllTurns()
            let i = turnState.currentIndex()
            triggerTurn(utterances[i])
            return "playing \(utterances[i].speaker)\n"
        case "stop":
            stopQA(clear: true)
            stopAllTurns()
            log("turns      ⏹ stopped")
            return "stopped\n"
        case "next":
            stopQA(clear: true)
            stopAllTurns()
            _ = turnState.advance(delta: 1, maxIndex: utterances.count - 1)
            log("turns      armed \(turnLine().trimmingCharacters(in: .whitespacesAndNewlines))")
            return turnLine()
        case "prev":
            stopQA(clear: true)
            stopAllTurns()
            _ = turnState.advance(delta: -1, maxIndex: utterances.count - 1)
            log("turns      armed \(turnLine().trimmingCharacters(in: .whitespacesAndNewlines))")
            return turnLine()
        case let jump where jump.hasPrefix("jump:"):
            let raw = String(jump.dropFirst("jump:".count))
            guard let requestedIndex = Int(raw) else {
                return "invalid jump index\n"
            }
            stopQA(clear: true)
            stopAllTurns()
            _ = turnState.jump(to: requestedIndex, maxIndex: utterances.count - 1)
            log("turns      armed \(turnLine().trimmingCharacters(in: .whitespacesAndNewlines))")
            return turnLine()
        case let qa where qa.hasPrefix("qa:"):
            let raw = String(qa.dropFirst("qa:".count))
            let question = raw.removingPercentEncoding?
                .trimmingCharacters(in: .whitespacesAndNewlines) ?? raw
            guard !question.isEmpty else {
                return "empty question\n"
            }
            stopAllTurns()
            stopQA(clear: true)
            log("qa         question: \(question)")
            do {
                let result = try runQAHelper(question: question)
                var loaded: [LoadedUtterance] = []
                for (offset, line) in result.lines.enumerated() {
                    guard let sourceDuck = DuckID.parse(line.duck) else {
                        continue
                    }
                    let targetDuck = args.duckAliases[sourceDuck] ?? sourceDuck
                    let player = makeFilePlayer(duck: targetDuck, loop: false)
                    let durationSec = try player.load(path: line.path)
                    let track = LoadedUtteranceTrack(sourceDuck: sourceDuck,
                                                     duck: targetDuck,
                                                     path: line.path,
                                                     player: player,
                                                     durationSec: durationSec)
                    loaded.append(LoadedUtterance(index: offset + 1,
                                                  speaker: line.speaker,
                                                  text: line.text,
                                                  tracks: [track],
                                                  durationSec: durationSec))
                    let aliasNote = sourceDuck == targetDuck
                        ? targetDuck.rawValue
                        : "\(sourceDuck.rawValue)→\(targetDuck.rawValue)"
                    log(String(format: "qa         %02d %@ %@ %.2fs %@",
                               offset + 1, line.speaker, aliasNote, durationSec,
                               (line.path as NSString).lastPathComponent))
                }
                guard !loaded.isEmpty else {
                    return "Q&A generated no playable lines\n"
                }
                qaLock.lock()
                qaQuestion = result.question
                qaUtterances = loaded
                qaLock.unlock()
                _ = qaState.jump(to: 0, maxIndex: loaded.count - 1)
                triggerQATurn(loaded[0])
                return "answering: \(loaded.map { $0.speaker }.joined(separator: " → "))\n"
            } catch {
                log("qa         failed: \(error.localizedDescription)")
                return "Q&A failed: \(error.localizedDescription)\n"
            }
        case "cue":
            return turnLine()
        case "state":
            return stateJSON()
        case "status":
            return transportStatusReport()
        case "health":
            return transportHealthReport()
        case "gain":
            return gainJSON()
        case let gain where gain.hasPrefix("gain:"):
            return handleGainControl(gain)
        default:
            return "unknown control: \(cmd)\n"
        }
    }

    log("turns      ARMED — \(utterances.count) utterance(s) loaded. \(turnLine().trimmingCharacters(in: .whitespacesAndNewlines))")
    log("turns      gap: \(String(format: "%.2f", gapSec))s")
    log("turns      trigger: curl http://localhost:\(args.port)/play")
    log("turns      next:    curl http://localhost:\(args.port)/next")
    log("turns      prev:    curl http://localhost:\(args.port)/prev")
} else if let playlistDir = args.playlistDir {
    if args.sine || args.mode1 {
        fputs("error: --playlist-dir is mutually exclusive with --sine / --mode1\n",
              stderr)
        exit(2)
    }
    let dirURL = URL(fileURLWithPath: playlistDir)
    let fm = FileManager.default
    guard let files = try? fm.contentsOfDirectory(at: dirURL,
                                                  includingPropertiesForKeys: nil)
    else {
        fputs("fatal: --playlist-dir \(playlistDir) could not be read\n", stderr)
        exit(1)
    }

    var grouped: [Int: [(path: String, duck: DuckID)]] = [:]
    for url in files {
        let stem = url.deletingPathExtension().lastPathComponent
        guard let partRange = stem.range(of: "_part", options: .backwards) else {
            continue
        }
        let rest = stem[partRange.upperBound...].split(separator: "_", maxSplits: 1)
        guard rest.count == 2,
              let part = Int(rest[0]),
              let duck = DuckID.parse(String(rest[1])) else {
            continue
        }
        grouped[part, default: []].append((path: url.path, duck: duck))
    }

    let cues: [LoadedCue] = grouped.keys.sorted().map { part in
        let entries = grouped[part]!.sorted { $0.duck.rawValue < $1.duck.rawValue }
        let tracks: [LoadedTrack] = entries.map { entry in
            let player = makeFilePlayer(duck: entry.duck, loop: false)
            var durationSec = 0.0
            do {
                let dur = try player.load(path: entry.path)
                durationSec = dur
                log(String(format: "playlist   part%02d %@ → %@ (%.1fs)",
                           part,
                           (entry.path as NSString).lastPathComponent,
                           entry.duck.rawValue,
                           dur))
            } catch {
                fputs("fatal: playlist load \(entry.path) failed: \(error.localizedDescription)\n",
                      stderr)
                exit(1)
            }
            return LoadedTrack(player: player, duck: entry.duck, path: entry.path,
                               durationSec: durationSec)
        }
        let durationSec = tracks.map(\.durationSec).max() ?? 0
        return LoadedCue(part: part, name: String(format: "part%02d", part),
                         tracks: tracks, durationSec: durationSec)
    }

    if cues.isEmpty {
        fputs("fatal: --playlist-dir \(playlistDir) contained no NAME_partNN_DX audio files\n",
              stderr)
        exit(1)
    }

    filePlayers = cues.flatMap { $0.tracks.map(\.player) }
    let playlistState = PlaylistState()
    let recoveryMonitor = RecoveryMonitor()

    @Sendable func cueLine() -> String {
        let cueIndex = playlistState.currentIndex()
        let cue = cues[cueIndex]
        let targets = cue.tracks.map { label($0.duck) }.joined(separator: ", ")
        return "cue \(cueIndex + 1)/\(cues.count): \(cue.name) → \(targets)\n"
    }

    @Sendable func stopAllPlaylistTracks() {
        for cue in cues {
            for track in cue.tracks { track.player.stop() }
        }
        for duck in Set(cues.flatMap { $0.tracks.map(\.duck) }) { transportReset(duck) }
        recoveryMonitor.cancel()
        playlistState.stop()
    }

    @Sendable func startRecoveryMonitor(generation: Int) {
        let timer = DispatchSource.makeTimerSource(queue: DispatchQueue.global(qos: .utility))
        timer.schedule(deadline: .now() + .seconds(1), repeating: .seconds(1))
        timer.setEventHandler {
            let snapshot = playlistState.snapshot()
            guard snapshot.playing, snapshot.generation == generation else { return }
            let cue = cues[snapshot.index]
            let targets = cue.tracks.map { $0.duck }
            var kicked = Set(server.kickWedgedConnections())
            for duck in duckStats.stalledDucks(targets: targets,
                                               playbackStartedAt: snapshot.startedAt) {
                if server.kick(duck) { kicked.insert(duck) }
            }
            if !kicked.isEmpty {
                let names = kicked.sorted { $0.rawValue < $1.rawValue }
                    .map { label($0) }
                    .joined(separator: ", ")
                log("recover    kicked \(names); waiting for reconnect")
            }
        }
        recoveryMonitor.replace(with: timer)
    }

    @Sendable func triggerCue(_ cue: LoadedCue) {
        let targets = cue.tracks.map { $0.duck }
        let names = targets.map { label($0) }.joined(separator: ", ")
        let present = targets.filter { transportIsConnected($0) }.count
        log("playlist   ▶ \(cue.name) \(names)  (\(present)/\(targets.count) ducks connected)")
        for duck in targets { duckStats.reset(duck) }
        for duck in targets { transportReset(duck) }
        let generation = playlistState.start(trackCount: cue.tracks.count)
        startRecoveryMonitor(generation: generation)
        for track in cue.tracks {
            track.player.rewind()
            let part = cue.name
            let id = track.duck.rawValue
            track.player.start(sharedClock: cue.tracks.count > 1,
                               onDone: {
                                   log("playlist   \(part) \(id) finished")
                                   guard playlistState.finish(generation: generation) else {
                                       return
                                   }
                                   let finishedIndex = playlistState.currentIndex()
                                   guard finishedIndex < cues.count - 1 else {
                                       log("playlist   complete")
                                       return
                                   }
                                   let nextIndex = playlistState.advance(delta: 1,
                                                                         maxIndex: cues.count - 1)
                                   log("playlist   auto-armed \(cueLine().trimmingCharacters(in: .whitespacesAndNewlines))")
                                   triggerCue(cues[nextIndex])
                               })
        }
    }

    @Sendable func stateJSON() -> String {
        let snapshot = playlistState.snapshot()
        let cue = cues[snapshot.index]
        let elapsedSec = snapshot.startedAt.map { min(Date().timeIntervalSince($0),
                                                      cue.durationSec) } ?? 0.0
        return """
        {"cue":{"index":\(snapshot.index),"count":\(cues.count),"name":"\(cue.name)","durationSec":\(String(format: "%.3f", cue.durationSec)),"generation":\(snapshot.generation),"elapsedSec":\(String(format: "%.3f", elapsedSec))},"playing":\(snapshot.playing ? "true" : "false"),"status":"\(jsonEscape(transportStatusReport()))","health":"\(jsonEscape(transportHealthReport()))"}

        """
    }

    server.onControl = { cmd in
        switch cmd {
        case "play":
            stopAllPlaylistTracks()
            let cueIndex = playlistState.currentIndex()
            let cue = cues[cueIndex]
            triggerCue(cue)
            return "playing \(cue.name)\n"
        case "stop":
            stopAllPlaylistTracks()
            log("playlist   ⏹ stopped")
            return "stopped\n"
        case "next":
            stopAllPlaylistTracks()
            _ = playlistState.advance(delta: 1, maxIndex: cues.count - 1)
            log("playlist   armed \(cueLine().trimmingCharacters(in: .whitespacesAndNewlines))")
            return cueLine()
        case "prev":
            stopAllPlaylistTracks()
            _ = playlistState.advance(delta: -1, maxIndex: cues.count - 1)
            log("playlist   armed \(cueLine().trimmingCharacters(in: .whitespacesAndNewlines))")
            return cueLine()
        case let jump where jump.hasPrefix("jump:"):
            let raw = String(jump.dropFirst("jump:".count))
            guard let requestedIndex = Int(raw) else {
                return "invalid jump index\n"
            }
            stopAllPlaylistTracks()
            _ = playlistState.jump(to: requestedIndex, maxIndex: cues.count - 1)
            log("playlist   armed \(cueLine().trimmingCharacters(in: .whitespacesAndNewlines))")
            return cueLine()
        case "cue":
            return cueLine()
        case "state":
            return stateJSON()
        case "status":
            return transportStatusReport()
        case "health":
            return transportHealthReport()
        case "gain":
            return gainJSON()
        case let gain where gain.hasPrefix("gain:"):
            return handleGainControl(gain)
        default:
            return "unknown control: \(cmd)\n"
        }
    }

    log("playlist   ARMED — \(cues.count) cue(s) loaded. \(cueLine().trimmingCharacters(in: .whitespacesAndNewlines))")
    log("playlist   trigger: curl http://localhost:\(args.port)/play")
    log("playlist   next:    curl http://localhost:\(args.port)/next")
    log("playlist   prev:    curl http://localhost:\(args.port)/prev")
    log("playlist   cue:     curl http://localhost:\(args.port)/cue")
} else if !args.plays.isEmpty {
    if args.sine || args.mode1 {
        fputs("error: --play is mutually exclusive with --sine / --mode1\n", stderr)
        exit(2)
    }
    // Load every track first (fail fast on a bad file before connecting).
    var loaded: [(player: FilePlayer, duck: DuckID)] = []
    for play in args.plays {
        let player = makeFilePlayer(duck: play.duck, loop: args.loop)
        do {
            let dur = try player.load(path: play.path)
            log(String(format: "play        %@ → %@ (%.1fs, 16k/mono, %@)",
                       (play.path as NSString).lastPathComponent, play.duck.rawValue,
                       dur, args.loop ? "looping" : "once"))
            loaded.append((player, play.duck))
        } catch {
            fputs("fatal: --play \(play.path) failed: \(error.localizedDescription)\n",
                  stderr)
            exit(1)
        }
    }
    filePlayers = loaded.map { $0.player }
    let targets = loaded.map { $0.duck }
    let multi = loaded.count > 1

    // Start (or restart) all loaded tracks together. Ducks are expected to be
    // already connected (that's the point of the control channel — no restart
    // churn). Rewinds first so every trigger replays from the top.
    let triggerPlay: @Sendable () -> Void = {
        let names = targets.map { label($0) }.joined(separator: ", ")
        let present = targets.filter { transportIsConnected($0) }.count
        log("play        ▶ \(names)  (\(present)/\(targets.count) ducks connected)")
        for duck in targets { transportReset(duck) }
        for entry in loaded {
            entry.player.rewind()
            let id = entry.duck.rawValue
            entry.player.start(sharedClock: multi,
                               onDone: { log("play        \(id) finished") })
        }
    }
    let triggerStop: @Sendable () -> Void = {
        for entry in loaded { entry.player.stop() }
        log("play        ⏹ stopped")
    }
    server.onControl = { cmd in
        switch cmd {
        case "play":
            triggerPlay()
            return "playing\n"
        case "stop":
            triggerStop()
            return "stopped\n"
        case "status":
            return transportStatusReport()
        case "health":
            return transportHealthReport()
        case "gain":
            return gainJSON()
        case let gain where gain.hasPrefix("gain:"):
            return handleGainControl(gain)
        default:
            return "unknown control: \(cmd)\n"
        }
    }

    if args.waitTrigger {
        log("play        ARMED — \(loaded.count) track(s) loaded, waiting for trigger.")
        log("play        trigger:  curl http://localhost:\(args.port)/play")
        log("play        stop:     curl http://localhost:\(args.port)/stop")
        log("play        status:   curl http://localhost:\(args.port)/status")
    } else if !multi {
        // Single track, auto-start: hold-cursor mode (resumes on reconnect).
        let only = loaded[0]; let id = only.duck.rawValue
        only.player.start(sharedClock: false, onDone: { log("play        \(id) finished") })
    } else {
        // Multi-track auto-start: wait until all ducks stably connected, then fire.
        DispatchQueue.global().async {
            let deadline = Date().addingTimeInterval(30)
            func allConnected() -> Bool { targets.allSatisfy { transportIsConnected($0) } }
            while Date() < deadline {
                if allConnected() { usleep(1_500_000); if allConnected() { break } }
                usleep(200_000)
            }
            triggerPlay()
        }
    }
}

// Graceful shutdown on SIGINT / SIGTERM.
let sigSrcInt  = DispatchSource.makeSignalSource(signal: SIGINT,  queue: .main)
let sigSrcTerm = DispatchSource.makeSignalSource(signal: SIGTERM, queue: .main)
signal(SIGINT,  SIG_IGN)
signal(SIGTERM, SIG_IGN)
let shutdown = {
    log("shutting down")
    sineGen?.stop()
    dawInput?.stop()
    filePlayers.forEach { $0.stop() }
    usbStage?.stop()
    server.stop()
    exit(0)
}
sigSrcInt.setEventHandler  { shutdown() }
sigSrcTerm.setEventHandler { shutdown() }
sigSrcInt.resume()
sigSrcTerm.resume()

dispatchMain()
